#include<stdio.h>
void display();//THIS IS FUNCTION PROTOTYPE WE CAN WRITE IT DOWN EASILY LIKE THIS WAY OR WE CAN WRITE FUNCTION DEFINATION EASILY WITH THE FUNCTION PROTOTYPE WITHOUT DECLEARING FUNCTION PROTOTYPE DIFFERENTLY. 
//WE CAN DECLARE FUNCTION DEFINATION BEFORE THE MAIN FUNCTION AND AFTER THE MAIN FUNCTION TOO.
void MORNING(){
    printf("GOOD MORNING\n");
}
void AFTERNOON(){
    printf("GOOD AFTERNOON\n");
}
void NIGHT(){
    printf("GOOD NIGHT\n");
}
int main(){
    printf("EXICUTING THE FUNCTION\n");
    MORNING();
    AFTERNOON();
    NIGHT();
}